[package]
name = "inv-store"
edition.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
inv-model = { workspace = true }
inv-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fs4 = { version = "0.13", features = ["sync"] }

[dev-dependencies]
tempfile = "3"
proptest = { workspace = true }
